Improve the error messages for functions that are not implemented
Rather than throwing JavaScript errors, throw native Python errors which
makes the error less confusing for users. Also, include the name of the
function that was called in the error message.

Instead of showing:

> pyodide.ffi.JsError: NotImplementedError

It now shows:

> NotImplementedError: <method name>